### ISSUE TITLE
Formatting bulleted lists

### ISSUE THREAD

**Issue by kovasap** [whonore/vim-sentencer#3]
Right now, lists like:

```
 - Item 1
 - item 2
```

Get formatted to 

```
 - Item 1 - item 2
```

When using `gqip` and sentencer's formatexpr.

**Comment by kovasap** [comment]
Actually nvm, I've having a hard time reproducing this

**Comment by whonore** [comment]
The plugin uses `formatlistpat` to recognize list headers, which are pretty whitespace-sensitive for some file types so it could be that you had something like `-item 2` so it treated it just as a normal line.

**Comment by kovasap** [comment]
Actually I'm still having this issue.  My config is at https://github.com/kovasap/dotfiles/blob/c019c08a052d7d0b19d7fec1f2aa08c2d8634cf1/.vim/after/ftplugin/markdown.vim and i'm pretty sure my `formatlistpat` is accurate.

**Comment by whonore** [comment]
I think the issue might be that some of the regex characters needs to be escaped. I can't find anywhere in the docs that says whether `formatlistpat` respects `magic` or not, so I'm not sure if this might affected by your other settings, but the following regex works for me:
```vim
let &formatlistpat='^\s*\d\+\.\s\+\|^\s*[-*+]\s\+\|^\[^\ze[^\]]\+\]:'
"                               ^ escape         ^ escape        ^ escape
```

**Comment by kovasap** [comment]
That works perfectly, thanks!  I wonder if this would be worth surfacing in the plugin README as a recommended config for markdown?
