### ISSUE TITLE
Spaces are removed when line length is longer than `textwidth`

### ISSUE THREAD

**Issue by devarops** [whonore/vim-sentencer#4]
Thank you for this great plugin. It works great using `gq`. However, I have an issue during typing.

When I exceed the maximum line length, my spaces are removed, and all the words are merged into a single word without spaces. This only happens after the line length is longer than `textwidth`.

**Comment by devarops** [comment]
A workaround is to set `textwidth=0`. If I do this, the problem is solved, but the text doesn't wrap automatically while I write. I have to use `gq` or `:[range]Sentencer`.
Is this the intended way to use the plugin?

**Comment by whonore** [comment]
Thanks for reporting. I personally usually disable automatic wrapping by setting `textwidth=0`, but I'd definitely like to support it. Could you help me reproduce the problem by telling me what your `textwidth` and `formatoptions` settings are and giving a small example I could try (something like, starting with the line "test test something something", enter insert mode and type "blah")?

**Comment by devarops** [comment]
Indeed, setting `textwidth=0` solves the issue for me.

My settings are: `textwidth=100` and `formatoptions=jtcqln`.

As an example, if I write in a new line:

```
One Two Three Four Five Six Seven Eight Nine Ten Eleven Twelve Thirteen Fourteen Fifteen Sixteen Seventeen Eighteen Nineteen Twenty.
```

Using `textwidth=0` and `gq` after I finished, I got the expected result:

```
One Two Three Four Five Six Seven Eight Nine Ten Eleven Twelve Thirteen Fourteen Fifteen Sixteen
Seventeen Eighteen Nineteen Twenty.
```

However, using `textwidth=100`, I get the following:

```
One Two Three Four Five Six Seven Eight Nine Ten Eleven Twelve Thirteen Fourteen Fifteen Sixteenn Twenty.
SeventeenEighteenNinetee                
```

**Comment by devarops** [comment]
Before `vim-sentecer`, I used [this](https://vi.stackexchange.com/a/2848) Stack Exchange answer. That allows me to hard wrap one sentence per line automatically while I write. But I prefer to use `vim-sentecer` because of its overflow allowance.

Not having automatic wrap while I write is not a deal breaker. But it is inconvenient since I have to toggle soft wrap while writing.

**Comment by whonore** [comment]
Thanks for the information, I'm able to reproduce the issue on my end. After a little experimentation, I think the issue is related to how the plugin moves the cursor around during formatting, but I'll need to look into it further.

**Comment by devarops** [comment]
That's great. Thank you for the update.

**Comment by whonore** [comment]
I think there's two issues: 
1. Whitespace is stripped from the end of the line even if it doesn't change otherwise. This means when Vim calls `formatexpr` while you're typing, but there are no new line breaks (as happens when `g:sentencer_overflow > 0` or `g:sentencer_textwidth < textwidth`) you lose the final space between the previous word and what you are currently typing.
2. The cursor is restored to the same position it was at before formatting. This means if you're typing and the line breaks, your cursor stays on the first line instead of moving down.

I have some ideas of how to fix these problems, but they're a bit tricky to get right, so it might take a couple days before I have enough time to fully implement them.

**Comment by devarops** [comment]
That makes sense. Thank you for looking into it.

In the meantime, I will be using _vim-sentencer_ with the option `textwidth=0` and `wrap` on, so this won't be an issue for me. No hurry.

Thank you for your time.

**Comment by whonore** [comment]
I opened a PR with a potential fix (#5). If you have time, it would be very helpful if you could try it out for a couple days and confirm that it fixes your issue and doesn't create any new ones. I added a bunch of tests, but there are so many corner cases.

**Comment by devarops** [comment]
Gladly. I'll try it out and report back. Thank you!

**Comment by devarops** [comment]
I've just installed the fix, and it is working as expected!

I'll keep testing it for a bit longer and report back again.

**Comment by devarops** [comment]
Unfortunately, this is still an issue when accented vowels (á, é, í, ó, ú) are in the sentence.

**Comment by whonore** [comment]
Do you have a specific example? There are some tests covering accented characters and everything I tried works as expected, but it's very possible that there's some corner case that is being missed.

**Comment by devarops** [comment]
Writing the following with `textwidth=100` and `sentencer_overflow=20`:

```
El blog es en español. No sé en qué idioma escribir el boletín. Por una parte, será sólo una fracción de ...
```
We expect this:

```
El blog es en español.
No sé en qué idioma escribir el boletín.
Por una parte, será sólo una fracción de ...
```
But we get this:

```
n de ...
El blog es en español.
No sé en qué idioma escribir el boletín.
Por una parte, será sólo una fracció
```

**Comment by devarops** [comment]
Writing the following with `textwidth=100` and `sentencer_overflow=20`:

```
Tal vez debería ser en español. Así puedo separar los idiomas escribiendo en inglés lo relacionado a Ciencia ...
```

We expect this:

```
Tal vez debería ser en español.
Así puedo separar los idiomas escribiendo en inglés lo relacionado a Ciencia ...
```
But we get this:

```
Tal vez debería ser en español.
Así puedo separar los idiomas escribiendo en inglés lo relacionado aCiencia ...
```

**Comment by whonore** [comment]
@devarops If you get a chance could you check if #6 solves this?

**Comment by devarops** [comment]
> @devarops If you get a chance could you check if #6 solves this?

I'll check it out.

**Comment by devarops** [comment]
Yes, it works great! 🎉
